name       : hwdata
version    : '0.323'
release    : 8
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.323.tar.gz : ab0ad297e30a1fe9d96fe27ef982d6a9f4e04e7b9977225954d9f1890b05d651
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
