name       : hwdata
version    : '0.305'
release    : 3
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.305.tar.gz : b3f33240d63ee8ce7620f58cf19ece127160447b6f525770718f2d0b23d53658
license    : GPL-2.0
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
