name       : hwdata
version    : '0.373'
release    : 17
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.373.tar.gz : 0db28dc635d5059ad23d068d2e56ef5dc540f95bc813ea5a3c0f5d63b03d20d6
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
