name       : hwdata
version    : '0.364'
release    : 12
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.364.tar.gz : e79ee7e0251c94273ac8ffa7f68892152d3cfc243a471bc61771d8ab53da3331
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
