name       : hwdata
version    : '0.366'
release    : 14
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.366.tar.gz : bdc91561ec210877e6d1e3ec3abf0305389d7bcc3bf616bcecb2bdf74e3a7696
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
