name       : hwdata
version    : '0.312'
release    : 5
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.312.tar.gz : 513d40c38ccc5ca6706d960dca61a9784d05c4a67a5e9c08f71b2d40acebab11
license    : GPL-2.0
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
