name       : hwdata
version    : '0.302'
release    : 2
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.302.tar.gz : 8af6051677d84fc6bcff8b0eb6ad92e877b74bfa5218e79d93d865a1b5083bb2
license    : GPL-2.0
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
