name       : hwdata
version    : '0.320'
release    : 7
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.320.tar.gz : 29c677f2ffef54181356224281fc12c14045f595d26254cc9b73f78d56284033
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
