name       : hwdata
version    : '0.369'
release    : 15
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.369.tar.gz : b17f3b81b887b9027fe5efa1ab1099afb472c843f89a9f5cc9ca4030b75bbdb2
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
