name       : hwdata
version    : 0.299
release    : 1
source     :
    - https://github.com/vcrhonek/hwdata/archive/v0.299.tar.gz : 791fce460cb980b5233e86d921e5b11fa321be2b7892437178b11346698738f1
license    : GPL-2.0
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
setup      : |
    %configure
install    : |
    %make_install
