name       : hwdata
version    : '0.365'
release    : 13
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.365.tar.gz : d6ae2436a69c6f5e04d926f5d753a99d90deb864065a2e2f8a8eda87b70dcdd5
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
